# name
name: hello_world

# trigger
on:
- push

# one or more jobs
jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
    - id: s00
      # running some shell bash command
      run: echo "current time in Github is $(date)"
    - id: s01
      # create a value and pass to the next step
      run: echo "CURR_DATE=$(date)" >> $GITHUB_OUTPUT
    - id: s02
      uses: mscoutermarsh/cowsays-action@master
      with: 
        text: 'moo mooooooo ${{ steps.s01.outputs.CURR_DATE }}'
        color: blue
    # - id: s01
    #   # cat the file
    #   run: cat hello.txt
    # - id: s02
    #   # list files
    #   run: ls -l